(*StartMovie "Amazon_App_Test"*)

SetDeviceOrientation "Portrait"
killapp "Amazon"
killApp "com.amazon.mShop.android.shopping"
wait 3
//Click "amazon_app"
launchapp "Amazon"
LaunchApp "com.amazon.mShop.android.shopping"
WaitFor 20, "amazon_banner"
Click "Search"
WaitFor 10, "Keyboard_Space"
TypeText "The Matrix DVD", returnKey
WaitFor 20, "Filter"
PressHomeButton
wait 3
killapp "Amazon"
killApp "com.amazon.mShop.android.shopping"

